### ISSUE TITLE
search url optimization & SQR (search queries report) : feedback

### ISSUE THREAD

**Issue by Hari-Bonda** [flamarkt/matomo#1]
Hello, i have recently started a feedback discussion about search url optimization & SQR (search queries report)

Clark sir asked to mention it in this discussion, I'm not sure its about SQR or URL optimization.

Do go through the below-mentioned URL to know more. sorry for not describing the context of the issue clearly here.

https://discuss.flarum.org/d/28571-flarum-search-url-optimization-needed

![image](https://user-images.githubusercontent.com/5230394/129026647-0edaac91-9d04-4521-b164-761e575997dc.png)

**Comment by clarkwinkelmann** [comment]
Hi, sorry I never noticed you opened an issue here.

If I remember correctly I mentioned this extension as it can help with inspecting the usage of the search feature as part of an SEO effort.

However I'm not planning to have this extension change the way Flarum builds its URLs. I feel this is best left to a separate extension.

Feel free to leave feature suggestions in the newly created discussion for this extension https://discuss.flarum.org/d/30500-flamarkt-matomo-analytics
